<?php include "includes/sections/header.php"; ?>
<?php //include "includes/sections/navbar.php"; ?>
<!-- heading sections -->

<?php
// checks if logged in ung user else pupunta sa logout.php to end session
if (!isset($_SESSION['userType'])){
    echo "<script>window.location='logout.php'</script>";
}
?>

<!-- put all the contents here  -->

<?php
    $dataArr = $_SESSION['reportMTS'];

    if (isset($_GET['start'])) {
      $start = $_GET['start'];
    }
    if (isset($_GET['end'])) {
      $end = $_GET['end'];
    }

?>
<br>
<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="text-center">
          <h2>Made-To-Stock Job Order Report</h2><br>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="card text-center">
          <div class="card-header">
            <?php if (isset($_GET['start'])): ?>
              <h3>Transactions between <?php echo $start; ?> and <?php echo $end; ?></h3>
            <?php endif; ?>
              <h3>Transaction Summary</h3>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover">
              <thead class="thead-light">
                <tr class="table-active">
                  <td>Order Date</td>
                  <td>Job Order ID</td>
                  <td>Product Name</td>
                  <td>Quantity</td>
                </tr>
              </thead>
              <tbody>

                <?php
                  foreach ($dataArr as $key => $value) {
                    $data = get_JODetails($conn,$value);

                    echo "<tr>";
                      echo "<td class='text-left'>";
                        echo $data['date'];
                      echo "</td>";

                      echo "<td>";
                        echo $value;
                      echo "</td>";

                      echo "<td>";
                        echo $data['productName'];
                      echo "</td>";

                      echo "<td>";
                        echo $data['quantity'];
                      echo "</td>";

                    echo "</tr>";

                  }
                 ?>
               </tr>
              </tbody>
            </table>
          </div>
          <div class="card-footer">
            <div class="text-center">
              <h4>***End of Report***</h4>
            </div><br><br>
            <div class="text-left text-muted">
              <p class="small">Generated by user: <?php echo get_username($conn,$_SESSION['userid']); ?>
                <br><?php echo date('F-d-Y g:i A'); ?>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>





<?php
  unset($_SESSION['reportMTS']);
 ?>
