<?php include "includes/sections/header.php"; ?>
<?php //include "includes/sections/navbar.php"; ?>
<!-- heading sections -->

<?php
// checks if logged in ung user else pupunta sa logout.php to end session
if (!isset($_SESSION['userType'])){
    echo "<script>window.location='logout.php'</script>";
}
?>

<!-- put all the contents here  -->

<?php
    $dataArr = $_SESSION['reportMTS'];
    //
    if (isset($_GET['start'])) {
      $start = $_GET['start'];
    }
    if (isset($_GET['end'])) {
      $end = $_GET['end'];
    }
    //
    $sum = 0;

    // $new = $_GET['data'];

?>
<br>
<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="text-center">
          <h2>Purchase Order Report</h2><br>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="card text-center">
          <div class="card-header">
              <?php if (isset($_GET['start'])): ?>
                <h3>Purchase Orders between <?php echo $start; ?> and <?php echo $end; ?></h3>
              <?php else: ?>
                <h3>Purchase Order Summary</h3>
              <?php endif; ?>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover">
              <thead class="thead-light">
                <tr class="table-active">
                  <td class="text-center">Purchase Order ID</td>
                  <td class="text-center">Supplier</td>
                  <td class="text-center">Raw Material</td>
                  <td class="text-center">Total Price</td>
                  <td class="text-center">Date Ordered</td>
                </tr>
              </thead>
              <tbody>

                <?php
                    foreach ($dataArr as $key => $value) {
                      $data = get_PODetail($conn,$value);
                      // print_p($data);
                      foreach ($data as $key => $value) {

                        echo "<tr>";
                            echo "<td class=''>";
                              echo $value['poid'];
                            echo "</td>";

                            echo "<td>";
                              echo get_suppname($conn,$value['suid']);
                            echo "</td>";

                            echo "<td>";
                              echo $value['rmname'];
                            echo "</td>";

                            echo "<td class='text-right'>";
                              echo number_format($value['sub']);
                            echo "</td>";

                            echo "<td class='text-center'>";
                              echo $value['odate'];
                            echo "</td>";



                        echo "</tr>";

                        $sum += $value['sub'];
                      }

                    }
                 ?>
               </tr>
              </tbody>
            </table>
          </div>
          <div class="card-footer">
            <div class="text-center">
              <h3>Total Expenses <?php echo number_format($sum); ?></h3>
              <h4>***End of Report***</h4>
            </div><br><br>
            <div class="text-left text-muted">
              <p class="small">Generated by user: <?php echo get_username($conn,$_SESSION['userid']); ?>
                <br><?php echo date('F-d-Y g:i A'); ?>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>





<?php
  // unset($_SESSION['reportMTS']);
 ?>
